# List of Python-related words used in the Hangman game
python_words: list[str] = [
    "TUPLE", "CLASS", "FLOAT", "INPUT", "PRINT",
    "WHILE", "BREAK", "ASYNC", "AWAIT", "SUPER",
    "GLOBAL", "LAMBDA", "IMPORT", "RETURN", "OBJECT",
    "METHOD", "STRING", "FORMAT", "APPEND", "REMOVE",
    "INSERT", "EXTEND", "SORTED", "FILTER", "REDUCE",
    "RANDOM", "CHOICE", "LOGGING", "EXCEPT", "FINALLY",
    "RAISE", "DECODE", "ENCODE", "MODULE", "SYNTAX",
    "INDENT", "KWARGS", "ARGS", "YIELD", "DEFINE",
    "UPDATE", "VALUES", "ITEMS", "LENGTH", "OUTPUT",
    "ERRORS", "BINARY", "BRANCH", "COMMIT", "BOOLEAN",
    "DECORATOR", "GENERATOR", "CONTEXT", "EXCEPTION", "INSTANCE",
    "ENCAPSULATE", "POLYMORPHISM", "ITERATOR", "DATACLASS", "FSTRING"
]
